# admin/config.yml
backend:
  name: auth0
  auth0_url: "dev-v4h0v1u1ezh0ca5u.us.auth0.com"
  app_id: "g6xNaVBZUj55tIBjIumTayN1JtRgf0Yy"

# publish_mode: simple # Can keep this or remove it, no impact on current error

media_folder: "static/uploads"
public_folder: "/static/uploads"


collections:
  - name: "pages" # Line 17, column 5 starts here. This MUST be indented correctly.
    label: "Site Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "pages/index.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/"}
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Subheadline", name: "subheadline", widget: "string"}
      - label: "Our Movement"
        name: "movement"
        file: "pages/movement.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/movement/"}
          - {label: "Main Title", name: "main_title", widget: "string"}
          - {label: "Main Description", name: "main_description", widget: "string"}
          - {label: "Broken System Title", name: "broken_system_title", widget: "string"}
          - {label: "Broken System Content", name: "broken_system_content", widget: "markdown"}
          - {label: "Movement Title", name: "movement_title", widget: "string"}
          - {label: "Movement Content", name: "movement_content", widget: "markdown"}
          - {label: "Principles Title", name: "principles_title", widget: "string"}
          - {label: "Principles", name: "principles", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "text"}]}
      - label: "The Ecosystem"
        name: "ecosystem"
        file: "pages/ecosystem.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/ecosystem/"}
          - {label: "Main Title", name: "main_title", widget: "string"}
          - {label: "Main Description", name: "main_description", widget: "string"}
          - {label: "Shoe Title", name: "shoe_title", widget: "string"}
          - {label: "Shoe Content", name: "shoe_content", widget: "markdown"}
          - {label: "Token Title", name: "token_title", widget: "string"}
          - {label: "Token Content", name: "token_content", widget: "markdown"}
          - {label: "March Title", name: "march_title", widget: "string"}
          - {label: "March Content", name: "march_content", widget: "markdown"}
          - {label: "Tech Title", name: "tech_title", widget: "string"}
          - {label: "Tech Content", name: "tech_content", widget: "markdown"}
      - label: "Our Mission"
        name: "mission"
        file: "pages/mission.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/mission/"}
          - {label: "Main Title", name: "main_title", widget: "string"}
          - {label: "Main Description", name: "main_description", widget: "string"}
          - {label: "Problem Title", name: "problem_title", widget: "string"}
          - {label: "Problem Content", name: "problem_content", widget: "markdown"}
          - {label: "Coordinated Effort Title", name: "coordinated_effort_title", widget: "string"}
          - {label: "Coordinated Effort Content", name: "coordinated_effort_content", widget: "markdown"}
          - {label: "Measuring Success Title", name: "measuring_success_title", widget: "string"}
          - {label: "Metrics", name: "metrics", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "text"}]}
      - label: "Join Us"
        name: "join-us"
        file: "pages/join-us.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/join-us/"}
          - {label: "Main Title", name: "main_title", widget: "string"}
          - {label: "Main Description", name: "main_description", widget: "string"}
          - {label: "Citizen Section Title", name: "citizen_section_title", widget: "string"}
          - {label: "Citizen Section Content", name: "citizen_section_content", widget: "markdown"}
          - {label: "Technologist Section Title", name: "technologist_section_title", widget: "string"}
          - {label: "Technologist Section Content", name: "technologist_section_content", widget: "markdown"}
          - {label: "Advocates Section Title", name: "advocates_section_title", widget: "string"}
          - {label: "Advocates Section Content", name: "advocates_section_content", widget: "markdown"}
          - {label: "FAQ Title", name: "faq_title", widget: "string"}
          - {label: "FAQs", name: "faqs", widget: "list", fields: [{label: "Question", name: "question", widget: "string"}, {label: "Answer", name: "answer", widget: "text"}]}
          - {label: "Connect Title", name: "connect_title", widget: "string"}
          - {label: "Connect Description", name: "connect_description", widget: "text"}
      - label: "Privacy Policy"
        name: "privacy-policy"
        file: "pages/privacy-policy.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/privacy-policy/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Last Updated", name: "last_updated", widget: "string"}
          - {label: "Main Content", name: "body", widget: "markdown"}
      - label: "Terms of Service"
        name: "terms-of-service"
        file: "pages/terms-of-service.liquid"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/terms-of-service/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Last Updated", name: "last_updated", widget: "string"}
          - {label: "Main Content", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.liquid"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/blog/{{year}}/{{month}}/{{day}}/{{slug}}/"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string", default: "GSP Team"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}